In [2]:
import torch
import numpy as np

array_np = np.array([[1, 2, 3],[4,5,6]])
array_pytorch = torch.tensor([[1,2,3],[4,5,6]])
print(array_np)
print(array_pytorch)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
x = torch.tensor([1,2,3], dtype = torch.float32)
y = torch.tensor([4,5,6], dtype = torch.float32)

In [4]:
x.shape

torch.Size([3])

In [5]:
x.dim()

1

In [6]:
x + y

tensor([5., 7., 9.])

In [7]:
x * y

tensor([ 4., 10., 18.])

In [8]:
x / y

tensor([0.2500, 0.4000, 0.5000])

In [9]:
torch.dot(x,y)

tensor(32.)

In [10]:
torch.dot(x,y).dim()

0

In [11]:
torch.dot(x,y).item()

32.0

In [12]:
x.mean()

tensor(2.)

In [13]:
x.std()

tensor(1.)

In [14]:
x.max()

tensor(3.)

In [15]:
x.argmax()

tensor(2)

In [16]:
y = x = torch.arange(0,9).reshape((3,3))
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [17]:
x.shape

torch.Size([3, 3])

In [18]:
x.dim()

2

In [19]:
x @ y

tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [20]:
x = torch.randn((2,3,1,10,10))
x.shape

torch.Size([2, 3, 1, 10, 10])

In [21]:
x.squeeze().shape

torch.Size([2, 3, 10, 10])

In [23]:
x.unsqueeze(dim = 4).shape

torch.Size([2, 3, 1, 10, 1, 10])

In [24]:
x = torch.arange(0, 100).reshape((2, 5, 10))
x

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]],

        [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
         [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [25]:
x.reshape((10, 10))

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
y = x.reshape((10,10))
y[0,0] = 100
print(y)
print(x)

tensor([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])
tensor([[[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]],

        [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  

In [ ]:
dsadsASfSsfasfas